name: release-pack
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - id: pack
        run: |
          PKG=$(npm pack --silent)
          echo "tgz=$PKG" >> "$GITHUB_OUTPUT"
      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.pack.outputs.tgz }}